### ISSUE TITLE
Custom iteration?

### ISSUE THREAD

**Issue by ValdarT** [JuliaData/CategoricalArrays.jl#119]
How should custom iteration be implemented over CategoricalArrays?

Or to put it differently, why do `next(CategoricalArray(["a","b","b"]), 2)` and `done(CategoricalArray(["a","b","b"]), 2)` give a `BoundsError`?

I'm on Julia v.0.6.2

**Comment by nalimilan** [comment]
How did you end up calling `next(x::CategoricalArray, 2)`? You're not supposed to pass `2` to it, it only accepts the state returned by a previous `next` call, starting with `next(x, start(x))`. If you want the next index, call `nextind`.

**Comment by ValdarT** [comment]
It's done in [DecisionTree.jl](https://github.com/bensadeghi/DecisionTree.jl/blob/master/src/DecisionTree.jl). Came across it while adding support for DataFrames - the package seems to handle features of `Array{String}` fine but errors on `CategoricalArrays` because of this.

**Comment by nalimilan** [comment]
OK, then that package should be changed not to assume that iteration state and indices are necessarily the same thing. Instead of calling `done(u.v, s)` [here](https://github.com/bensadeghi/DecisionTree.jl/blob/55fcfd9fff1701d982c57637b6e380c460a08737/src/DecisionTree.jl#L59), it should use `checkbounds(Bool, u.v, s)`. Also for full generality `start(u)` should return `first(linearindices(u))` rather than 1.
