### ISSUE TITLE
add future to require

### ISSUE THREAD

**Issue by kafisatz** [JuliaData/CategoricalArrays.jl#149]
Can you possibly add Future to  the require (or manifest/project.toml)?

I am getting this error on travis

https://travis-ci.org/kafisatz/DecisionTrees.jl/jobs/394917060#L580

**Comment by ararslan** [comment]
I'm not sure why we're using Future at all here (or why it needs to exist, but that's beside the point). We should just be using `copyto!`.

**Comment by nalimilan** [comment]
We need it to add methods to `Future.copy!` and to test that it works. I added this when porting to 0.7 so that we keep the tests for `copy!` and yet do not trigger the deprecation. I'm not sure what's the best solution here: we can't add `Future` to REQUIRE without dropping 0.6 support. Maybe we should just do that.
