### ISSUE TITLE
Problem with bounds checking

### ISSUE THREAD

**Issue by ablaom** [JuliaData/CategoricalArrays.jl#173]
In Julia 1.0.2:

````julia
using CategoricalArrays

struct Rows end
Base.getindex(v::AbstractVector, ::Type{Rows}, r) = getindex(v, r)
v=CategoricalArray(["a","b","b"])

v[Rows, 1]
````

throws:

````
ERROR: ArgumentError: unable to check bounds for indices of type DataType
Stacktrace:
 [1] checkindex(::Type{Bool}, ::Base.OneTo{Int64}, ::Type) at ./abstractarray.jl:504
 [2] checkbounds at ./abstractarray.jl:475 [inlined]
 [3] checkbounds at ./abstractarray.jl:449 [inlined]
 [4] getindex(::CategoricalArray{String,1,UInt32,String,CategoricalString{UInt32},Union{}}, ::Type, ::Int64) at /Users/anthony/.julia/packages/CategoricalArrays/rQrLR/src/array.jl:541
 [5] top-level scope at none:0
````

**Comment by nalimilan** [comment]
What makes you think it's a bug in CategoricalArrays? `AbstractArray` implementations are not required to support indexing with any arbitrary type. It works for `Array` only because the method you define is more specific than the fallback, so it's called directly.

**Comment by nalimilan** [comment]
That doesn't work because that method isn't even called. You need to define a more specific method than the one defined in CategoricalArrays, for example something like `Base.getindex(v::CategoricalArray ::Type{Rows}, r)`.

BTW, I think it would be more idiomatic to define `rows = Rows()` or `ROWS = Rows()`, and have the method be `Base.getindex(v::CategoricalArray ::Rows, r)` instead. See https://docs.julialang.org/en/latest/manual/style-guide/#Avoid-confusion-about-whether-something-is-an-instance-or-a-type-1.

**Comment by ablaom** [comment]
Great, that works. Many thanks.
