### ISSUE TITLE
sorting an unordered CategoricalString

### ISSUE THREAD

**Issue by bkamins** [JuliaData/CategoricalArrays.jl#185]
Is this intended?

```
julia> c = categorical(["E","A","B"])
3-element CategoricalArray{String,1,UInt32}:
 "E"
 "A"
 "B"

julia> sort(c)
3-element CategoricalArray{String,1,UInt32}:
 "A"
 "B"
 "E"

julia> levels!(c, Vector{String}(c))
3-element CategoricalArray{String,1,UInt32}:
 "E"
 "A"
 "B"

julia> sort(c)
3-element CategoricalArray{String,1,UInt32}:
 "E"
 "A"
 "B"
```

At least for me it is unintuitive. The practical problem is that `CSV.read` orders levels as they appear in source (as opposed to `CategoricalArray` constructor which sorts them).

**Comment by nalimilan** [comment]
Yes, that's intended, but `CSV.read` should sort levels in lexicographic order by default. I fixed a bug about this recently so I think it works. Do you have an example where it doesn't?

**Comment by bkamins** [comment]
This problem came up when I was making a PR for the statistics book. I am on CSV v0.4.3.

If this is intended then the problem is that when you do something like:
```
julia> x = categorical([3,2,1])
3-element CategoricalArray{Int64,1,UInt32}:
 3
 2
 1

julia> push!(x, 0)
4-element CategoricalArray{Int64,1,UInt32}:
 3
 2
 1
 0

julia> levels(x)
4-element Array{Int64,1}:
 1
 2
 3
 0
```
the levels do not remain sorted and it seems a bit inconsistent (this is especially problematic for strings which behave like normal strings otherwise).

**Comment by nalimilan** [comment]
> This problem came up when I was making a PR for the statistics book. I am on CSV v0.4.3.

But can you reproduce this with a small example?

Indeed when you push values they get added at the ends of levels, but the only other option is to throw an error (like we do when the array is ordered). We could sort values according to their original order (lexicographic for strings), but then that would be inconsistent with the goal of using the user-defined ordering... For example, with the current sorting behavior, a plotting system will sort values in the expected order even without being aware of CategoricalArrays.

I agree there's an inconsistency due to the fact that `CategoricalString <: AbstractString`. But I'm not sure it's a serious issue in practice.

**Comment by bkamins** [comment]
> But can you reproduce this with a small example?

This is pretty basic. You read in data with `CSV.read` with `categorical=true` the levels are stored in the order of appereance. Then you want to plot some data, but you want to order them alphabetically and sorting the `DataFrame` fails because of the order `CSV.read` assigned (actually it is no-op as the order is the order of appearance). So of course one solution is to do `levels!(catvec, sort(levels(catvec))` and then sort the data frame, but this is ugly. The issue is that this leads you to reading-in the data as `String`s and sorting the data frame using string order.

But I understand you say you have fixed this on CSV.jl master, so I guess this issue will be gone soon.

**Comment by nalimilan** [comment]
OK, I thought https://github.com/JuliaData/CSV.jl/pull/377 had been released, but actually that's not the case yet.

**Comment by nalimilan** [comment]
Does that still happen with CSV 0.5? I'd guess not.

**Comment by bkamins** [comment]
CSV 0.5 works ok
