### ISSUE TITLE
Abstraction for AbstractString and Number

### ISSUE THREAD

**Issue by Nosferican** [JuliaData/CategoricalArrays.jl#186]
I believe one advantage to separating `CategoricalString` and `CategoricalValue` is for proper abstraction. `CategoricalString <: AbstractString`, but `CategoricalValue <: Any`. It would make more sense for `CategoricalValue <: Number` and define the API (e.g., `+`, `-`, `*`, `/`, `^` etc.)

**Comment by nalimilan** [comment]
`CategoricalValue` is not necessarily a number. I think one of the common use cases is `CategoricalValue{Char}`. Anyway categorical values should probably not support arithmetic since numbers are likely to represent categories (obviously) which are not necessarily "real" values.

What's your use case for this?

**Comment by Nosferican** [comment]
Been pretty busy in the last few day or so, so I can't even recall. I guess it seems generally useful for the values to keep their properties even as categorical, for example `AbstractCategoricalVector{<:TimeType}` and such. It is certainly the case with `CategoricalString`. Guess the issue would be to consider allowing the underline properties of the values even at `Categorical`...

**Comment by nalimilan** [comment]
But why not keep these in a plain `Array` then? At any rate Julia doesn't allow subtyping an arbitrary type at the moment, which is why we special-cased strings.

**Comment by nalimilan** [comment]
We're actually going to remove `CategoricalString` to simplify things, so closing.
