### ISSUE TITLE
[question] giving pre-computed unique values to categorical constructor

### ISSUE THREAD

**Issue by tlienart** [JuliaData/CategoricalArrays.jl#210]
I would like to construct a `CategoricalArray` when I already have the unique values of that array computed. I'm assuming this should help avoid un-necessary re-computations (?). Is it possible to use something like the `categorical` function to achieve this?

The use case is as follows: in MLJ we have some machinery to try to determine automatically what kind of feature is given; one of the heuristic the user can choose to use is that there are relatively few values in that column (e.g. say only three unique values compared to 100 rows). In order to see whether that's relevant we compute the number of unique values and then eventually we may use `categorical` but this seems to me wasteful if `categorical` ends up looking for all the unique values once more?

Thanks

**Comment by nalimilan** [comment]
With the current design, it doesn't really make a performance difference if you know the levels in advance: anyway, we have to go over the vector, and lookup each value in a dict to obtain the integer reference. Adding the levels progressively as we encounter them rather than adding them beforehand should be equivalent (the former could even be slightly faster by avoiding hashing twice for unique values, but that's really negligible). I guess the latter could be slightly faster if we called `sizehint!` on the dictionary before adding levels to avoid resizing it, but that shouldn't be significant (just try it by yourself with a `Dict{String,UInt32}`), especially with a small number of levels.

Knowing levels in advance could matter if we dropped the distinction between `index` and `levels`, as sorting levels in lexicographic order would require updating all integer codes once we've been over all values. If we dropped that distinction (which is mostly useful only in that case, and has a complexity cost), then passing the unique levels in their final order would help.

Anyway, adding a `levels` keyword argument to `categorical` wouldn't be absurd, disregarding performance issues.

**Comment by tlienart** [comment]
ok thanks that makes sens

**Comment by nalimilan** [comment]
See also https://github.com/JuliaData/CategoricalArrays.jl/issues/84.

**Comment by nalimilan** [comment]
For reference, `categorical` now accepts a `levels` keyword argument, which is more efficient than calling `levels!` after the fact since in the new design we have to recompute reference codes when reordering levels.
