### ISSUE TITLE
cut produces duplicate levels

### ISSUE THREAD

**Issue by bkamins** [JuliaData/CategoricalArrays.jl#244]
See:
```
julia> levels(cut([zeros(1000); ones(1000)], 10))
8-element Array{String,1}:
 "[0.0, 0.0)"
 "[0.0, 0.0)"
 "[0.0, 0.0)"
 "[0.0, 0.5)"
 "[0.5, 1.0)"
 "[1.0, 1.0)"
 "[1.0, 1.0)"
 "[1.0, 1.0]"

julia> unique(levels(cut([zeros(1000); ones(1000)], 10)))
5-element Array{String,1}:
 "[0.0, 0.0)"
 "[0.0, 0.5)"
 "[0.5, 1.0)"
 "[1.0, 1.0)"
 "[1.0, 1.0]"
```

@nalimilan - I feel this is a serious problem with cut.

**Comment by nalimilan** [comment]
Good catch. That's a really bad situation in which it's hard to do something meaningful. https://github.com/JuliaData/CategoricalArrays.jl/pull/245 turns this into an error, in which case the user can simply reduce the number of requested quantiles. What do you think?

For reference, R's `cut2` in the Hmisc package does this:
```R
> > levels(Hmisc::cut2(rep(0:1, 1000), g=10))
[1] "0" "1"
Warning message:
In min(xx[xx > upper]) : no non-missing arguments to min; returning Inf
```
That makes sense, but it could also be misleading, and the warning clearly isn't intended to help the user.

Stata silently generates duplicate breaks. `xtile` returns the index of the lowest interval which matches; but since it doesn't give labels to these indices, it doesn't really have to decide what to do with duplicate labels. `cut` returns the index of the highest interval which matches; when asked to return labels instead, it creates duplicate labels with different codes (like we incorrectly do now). All that sounds quite inconsistent.

**Comment by bkamins** [comment]
Thank you for looking into this.
