### ISSUE TITLE
Very slow copyto! in corner cases

### ISSUE THREAD

**Issue by bkamins** [JuliaData/CategoricalArrays.jl#308]
We have:
```
julia> using CategoricalArrays

julia> x = categorical(1:10^6);

julia> y = similar(x, 10); xx=x[1:10]; @time copyto!(y, xx);
  0.852741 seconds (2.76 M allocations: 299.510 MiB, 30.30% gc time)

julia> y = similar(x, 10); xx=x[1:10]; @time copyto!(y, xx);
  0.507202 seconds (2.00 M allocations: 261.165 MiB, 41.89% gc time)

julia> y = similar(x, 10); xx=x[1:10]; @time copyto!(y, xx);
  0.506432 seconds (2.00 M allocations: 261.165 MiB, 38.23% gc time)
```
which is very slow.

This is a very common pattern. I propose to create a fast path in `copyto!` which checks if `isempty(levels(y))` and in this case just copies the pool and refs from `x` to `y`.

A rough implementation could be:
```
function Base.copyto!(dest::T, src::T) where {T <: CategoricalArray}
    if length(dest.pool) == 0
        length(dest) == length(src) || throw(DimensionMismatch())
        dest.pool = copy(src.pool)
        dest.refs = copy(src.refs)
    else
        invoke(copyto!, Tuple{typeof(dest), AbstractArray}, dest, src)
    end
    return dest
end
```

@nalimilan - you know the internals better so something more refined might be preferred.

**Comment by nalimilan** [comment]
Indeed the fast path was too restrictive. But it turns out there were two other bottlenecks. See https://github.com/JuliaData/CategoricalArrays.jl/pull/309.

Though the result remains slow because creating a large pool is costly, and I don't see any way around that. CategoricalArrays are not optimized for situations where the number of levels is large compared to the number of entries. Have you hit this in a real situation?

**Comment by bkamins** [comment]
No - I only hit it when stress-tesing `unstack`. Anyway - please feel free to decide what to do with this issue as you know the source code best here.
