### ISSUE TITLE
contrasts

### ISSUE THREAD

**Issue by dmbates** [JuliaData/CategoricalArrays.jl#4]
On the julia-stats mailing list I suggested exporting a `constrasts` generic from `StatsBase` and adding methods in this repository.  I would appreciate your comments, @nalimilan, if you have any.

**Comment by nalimilan** [comment]
Sorry for not replying, I had totally missed this issue. I'm not sure this package is the best place to add these methods, since one can perfectly work with categorical data without `CategoricalArray`. I'd rather have them in a (say) ModelsBase package, together with functions currently living in StatBase's `src/statmodels/` directory.

@kleinschmidt What's your opinion regarding this?

**Comment by kleinschmidt** [comment]
I agree. I think we'd also talked about incorporating the things in DataFrames `src/statsmodels`, too, but I'm not sure whether that belongs in a `ModelsBase` package since it's specific to tabular data.

**Comment by nalimilan** [comment]
All of this is implemented in StatsModels now.
