### ISSUE TITLE
Slow creation of CategoricalArrays from array of strings

### ISSUE THREAD

**Issue by xiaodaigh** [JuliaData/CategoricalArrays.jl#93]
The timings for coverting an array of strings to CategoricalArray is really slow.

```julia
using CategoricalArrays
import CategoricalArrays.CategoricalArray
const N = 250_000_000
const K = 100
@time pool1 = [@sprintf "id%010d" k for k in 1:(N/K)]
@time id3 = rand(pool1, N)

# very slow
@time a = CategoricalArray(id3, ordered=false)
```

**Comment by nalimilan** [comment]
How do you define "very slow"? Do you know a faster method?

**Comment by xiaodaigh** [comment]
I think the creation of the categorical array from a vector of strings should take roughly the same amount of time as counting the number of unique elements? Again this is just a version of `sumby` using Dict-based methods. From my own timing it should take around 2mins on my computer but currently took more than 10 mins.

**Comment by nalimilan** [comment]
OK. I don't think anybody has done serious benchmarking of this. We currently simply call `copy!` to fill the categorical array, and therefore rely on `setindex!` to check whether the level already exist, or create a new level if not. It looks like we could add `@inline` to `get!` since the compiler doesn't appear to inline it automatically, and that function is called for each entry. If that's not enough we could write our own loop, but I'd rather do that only if it's really needed.

It would be cool to add a benchmark like the one you posted above to benchmarks.jl to track improvements.

**Comment by nalimilan** [comment]
OK, it turns out the problem was in `levels!`, which was pathologically slow when checking whether some levels were dropped (see https://github.com/JuliaLang/julia/issues/24624). I've fixed that, but actually we can call `levels!` directly on the pool to skip this check since we know the levels are all preserved. See #100.

Thanks for spotting this @xiaodaigh. Please feel free to report any other performance issues you may find, as the package hasn't been thoroughly benchmarked yet (though it is designed to allow for very efficient operation).
