### ISSUE TITLE
No efficient way to generate a categorical array or hard to discover 

### ISSUE THREAD

**Issue by xiaodaigh** [JuliaData/CategoricalArrays.jl#94]
No efficient way to generate a categorical array, or it's really hard to discover.

```julia
CategoricalArray([1, 2, 1, 3], CategoricalPool(["a","b","c"],false))
```

to me the above should generate the Array ["a", "b", "a", "c"] or even simpler

```julia
CategoricalArray([1,2,1,3], ["a","b","c"])
```

Otherwise it doesn't feel intuitive

**Comment by alyst** [comment]
What you are referring to is the inner constructor of `CategoricalArray`. For the `master` version of the package the proper call should look like:
```julia
CategoricalArray{String, 1}(UInt32[1, 2, 1, 3], CategoricalPool(["a", "b", "c"], false))
```
It's a low-level operation that is not supposed to be called directly, because it requires that the type parameters match each other, the references match the levels in the pool etc.
It could be changed between package versions without prior notice. That's also why it's not mentioned in the docs.

Could you describe your use case more specifically? Maybe there's a more convenient way to create categorical array using e.g. `categorical(["a", "b", "a", "c"])` call.

**Comment by nalimilan** [comment]
Maybe you're looking for `recode`.
